### ISSUE TITLE
请教下，如果用的英文版 academicpages，怎么设置您repo上的那个中英文语言转化按钮？

### ISSUE THREAD

**Issue by Ricksanchez000** [tangjyan/zh-cn#5]
请教下，如果用的英文版 academicpages，怎么设置您repo上的那个中英文语言转化按钮？ 
因为我的页面可能涉及中文和英文用户，十分感谢您的帮助。

**Comment by tangjyan** [comment]
> 请教下，如果用的英文版 academicpages，怎么设置您repo上的那个中英文语言转化按钮？ 因为我的页面可能涉及中文和英文用户，十分感谢您的帮助。

![image](https://github.com/user-attachments/assets/43e05a1b-0fec-4db7-a9e4-7fd5921180dc)
其实就是改了原模版中的Homepage按钮，应该是在这个文件中改的链接地址，加了一个好看的图标就行了
